### ISSUE TITLE
feature request: 24bit color

### ISSUE THREAD

**Issue by jason-green-io** [pblop/twitch-chat#21]
Since I think 1.16, chat messages can be 24bit colours using `#AAAAAA` or whatever. Not sure if Fabric has that ability when inserting in chat, but the vanilla client does via `/tellraw` json. You know Twitch provides that info since I see you find the closest basic Minecraft colour match. It would be nice to get the correct colours from Twitch, I sometimes see certain shades of red get converted to grey.

**Comment by pblop** [comment]
That looks doable! I've been looking at the functions I use to colour messages and at least on the surface that looks like both an improvement and a way to reduce my horrible color translation code. 😆

I'll be chaning that and pushing it in a few weeks, I'm in the process of moving

**Comment by jason-green-io** [comment]
I think the only issue you'll run into is supporting older versions of client that do not support 24 bit color in chat. You might have to keep your mess around to fall back with < 1.16 .. unless Fabric API takes care of this for you?

**Comment by pblop** [comment]
Yeah that won't be a problem because I only support the latest version. 😅 
I'd have to maintain several codebases if I wanted to support more than one version, and that's too much work!

**Comment by jason-green-io** [comment]
Have you had a chance to work on this?

**Comment by pblop** [comment]
Current status of this issue: I tried to do this. Turns out it was harder because of the way Twitch gives me the user colours (not all at once, sometimes after I need it so I would need a placeholder, which would kind of break the spirit of 24-bit name colours).
So this will probably be added when I upgrade the way I talk to Twitch (I'm using a general-purpose library that's updated very sparingly and doesn't really support Twitch that well, and will be switching to a Twitch-only library that will hopefully allow me to handle stuff like colours better).

**Comment by jason-green-io** [comment]
Pretty sure with tags enabled, every PRIVMSG has a tag with the color of the user.

https://dev.twitch.tv/docs/irc/tags#privmsg-twitch-tags

**Comment by jason-green-io** [comment]
Something else I ran across .. that you may already be doing but though of adding it here anyway. For users who haven't set their colour, the web gui assign a color based on their username. Documented here: https://discuss.dev.twitch.tv/t/default-user-color-in-chat/385

I noticed some users didn't have color data in their tags, this is why they have color on the web client, but not when reading from IRC.
